version: '3.8'
services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    networks:
      - evfhq-database

volumes:
  postgres-data:

networks:
  evfhq-database:
    name: evfhq-database  
